# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Yggshka
tagline:             'Hearthstone analytics'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://yggshka.github.io
baseurl:             '/hs'
paginate:            5

# About/contact
author:
  name:              Pavel Pavlenko
  url:               https://twitter.com/yggshka
  email:             yggshka@gmail.com

# Custom vars
version:             1.0.0
